version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Budapest
  open-pull-requests-limit: 10
  versioning-strategy: increase
  commit-message:
    prefix: build
    include: scope
