parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: 
    - ./tsconfig.json
    - ./tsconfig.spec.json
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'prettier'
rules:
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/no-parameter-properties': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - args: 'none'
