name: Auto approve PRs
on:
  pull_request
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
