name: Dependabot auto-merge
on:
  pull_request
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: 'Auto approve PR'
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.SM_GH_TOKEN }}"
    - name: 'Merge'
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.SM_GH_TOKEN}}
        script: |
          await github.issues.createComment({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            issue_number: context.payload.pull_request.number,
            body: '@dependabot squash and merge'
          })
